INSERT INTO ovas (description, idcurso, nombre) VALUES ('Introducción a sistemas operativos', 101, 'OVA de Sistemas');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Métodos numéricos básicos', 102, 'OVA de Matemáticas');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Gestión de costos y presupuestos', 103, 'OVA de Contabilidad');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Fundamentos de lógica', 104, 'OVA de Discretas');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Programación avanzada en C++', 105, 'OVA de Programación');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Optimización de recursos en memoria', 106, 'OVA de Memoria');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Introducción al diseño modular', 107, 'OVA de Arquitectura');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Conceptos básicos de PostgreSQL', 108, 'OVA de Bases de Datos');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Fundamentos de Docker y despliegue', 109, 'OVA de Deploy');
INSERT INTO ovas (description, idcurso, nombre) VALUES ('Validación de datos en Spring Boot', 110, 'OVA de Backend');